/**
 * TypeScript AppHost Example for .NET Aspire 13.2
 * 
 * This demonstrates the new TypeScript AppHost feature where you can
 * define your application's architecture using TypeScript instead of C#.
 * 
 * Key points:
 * - Uses async/await syntax (TypeScript style)
 * - Same orchestration power as C# AppHost
 * - Integration SDKs auto-generated in .modules/ folder
 * - Service discovery and telemetry work the same way
 */

// The aspire.js module is generated by 'aspire restore'
// It provides TypeScript bindings to Aspire's orchestration capabilities
import { createBuilder } from './.modules/aspire.js';

async function main() {
    console.log('🚀 Starting TypeScript AppHost...');

    const builder = await createBuilder();

    // Add .NET API service
    const api = await builder.addProject("api", "./services/api/ApiService/ApiService.csproj", "http")
        .withEnvironment("GREETING", "Hello from TypeScript AppHost!");

    // Add Node.js frontend as an executable
    const frontend = await builder.addExecutable("frontend", "node", "./services/frontend", ["server.js"])
        .withReference(api)
        .withExternalHttpEndpoints()
        .withEnvironment("NODE_ENV", "development");

    console.log('✅ AppHost configured successfully');

    await builder.build().run();
}

// Run the AppHost and handle errors
main().catch((error) => {
    console.error('❌ AppHost failed to start:', error);
    process.exit(1);
});
